---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "/e2e"
    groups:
      cypress:
        patterns:
          - "@bahmutov/cypress-esbuild-preprocessor""
          - "@bahmutov/cypress-esbuild-preprocessor"
          - "cypress"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    versioning-strategy: increase
